name: Scrape and Upload Cache

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時執行一次
  workflow_dispatch:

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    env:
      LEAPCELL_API_URL: ${{ secrets.LEAPCELL_API_URL }}
      LEAPCELL_API_KEY: ${{ secrets.LEAPCELL_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium

      - name: Run scraper and upload cache
        run: python update_and_upload.py
