name: Update Cache Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時的整點執行一次 (UTC時間)
  workflow_dispatch:      # 允許手動觸發

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: playwright install

    - name: Run Cache Update Script
      run: |
        python update_cache.py  # 這是你剛剛建立的

    - name: Show cache.json content
      run: cat cache.json

    - name: Check git status and diff
      run: |
        git status
        git diff

    # 這個可以保留：如果你想同步 GitHub 上的 cache.json
    - name: Commit and Push cache.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cache.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update cache.json by scheduled job"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/oounjh/Infopaw.git
        fi
      continue-on-error: true
