name: Update Cache Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # 每兩小時的整點執行一次 (UTC時間)
  workflow_dispatch:      # 允許手動觸發

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 你的爬蟲依賴

    - name: Run Cache Update Script
      run: |
        python your_scraper_script.py    # 執行你的爬蟲腳本，輸出 cache.json

    - name: Commit and Push cache.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cache.json
        git commit -m "Update cache.json by scheduled job"
        git push
      continue-on-error: true  # 如果沒變動不會失敗

    - name: Call Render Cache Upload API
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://infopaw.onrender.com//upload_cache?key=your_cache_key" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          --data @cache.json
